name: Release

on:
  push:
    branch:
      - "main"

jobs:
  release:
    runs-on: ${{ matrix.env.os }}
    strategy:
      matrix:
        env: [
          { os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
          { os: windows-latest, target: x86_64-pc-windows-msvc }
          { os: macos-latest, target: x86_64-apple-darwin }
        ]

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Set up target
      run: rustup target add ${{ matrix.env.target }}

    - name: Build release binary
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target ${{ matrix.env.target }} --release

    - run: "ls target/release"

    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        prerelease: true
        files: |
          target/release/chatgpt-cli*
